# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0686daa82cc485ef4a76cc47f396a5001a7a076865da59960fc8fb51e40dde5c4dc1dbc8cbaa05db45ab68678be915a684e7d0d93a5d443adcecdd5ff43081c

test:
  secret_key_base: de1dfb351c9da9cec28059da6aa2557b8a6ebd7d9ce55dc66f155c4b3e63d74e9ee5b27c6fbdc26f1c0991ce0afcb82be24d8d91bb1c391dfd18de6362687f55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
